HW10 is completed
roman-grefenstein/otus_home_work pull request #13
Opened 2021-03-31 07:49 UTC by roman-grefenstein

## Домашнее задание №10 «Оптимизация программы»

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-04-03 05:49 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/149277/9022/

Здравствуйте!
Интересное решение, но хотелось бы обсудить/чуть переделать.

2021-04-03 05:49 UTC, Antonboom commented on hw10_program_optimization/stats.go
> +func countDomains(u *users, domain string) DomainStat {
у вас users слайс, копируется только слайс-хедер, передавать по указателю подобные типы не нужно

2021-04-03 05:49 UTC, Antonboom commented on hw10_program_optimization/stats.go
> +		line := scanner.Text()
может работать с байтами? чтобы избежать лишних копирований

scanner.Bytes()

2021-04-03 05:49 UTC, Antonboom commented on hw10_program_optimization/stats.go
> +		if strings.Contains(line, domainStr) {
это хак, по сути вы не знаете, что там в этих данных и мне кажется странным полагаться на вхождение туда байтов домена

более железно хотелось бы получить:
- десериализация JSON
-  проверка
- добавление

2021-04-03 05:49 UTC, Antonboom commented on hw10_program_optimization/stats.go
> +			lines = append(lines, line)
а нужно ли нам накапливать строки? если файл будет 100ГБ и в каждой строчке будет почта с таким доменом?

2021-04-03 05:49 UTC, Antonboom commented on hw10_program_optimization/stats.go
> +		result = append(result, user)
аналогично, а нужно ли нам вообще накапливать что-то?

нельзя ли сразу считать домены?

2021-04-03 15:16 UTC, roman-grefenstein commented
@Antonboom внес правки и поменял библиотеку для работы с json, так как fastjson для данной задачи оказался и по памяти в выигрыши и по времени обработки. Посмотрите, пожалуйста

```
jsoniter

=== RUN   TestGetDomainStat_Time_And_Memory
stats_optimization_test.go:44: time used: 297.315196ms
stats_optimization_test.go:45: memory used: 14Mb
--- PASS: TestGetDomainStat_Time_And_Memory (5.23s)
PASS


fastjson

=== RUN   TestGetDomainStat_Time_And_Memory
stats_optimization_test.go:44: time used: 273.295969ms
stats_optimization_test.go:45: memory used: 5Mb
--- PASS: TestGetDomainStat_Time_And_Memory (4.41s)
PASS
```

2021-04-04 18:03 UTC, Antonboom approved these changes
Да, к fastjson вопросов не было.
Супер!

Принято
10 / 10

2021-04-04 18:03 UTC, Antonboom commented on hw10_program_optimization/stats.go
> +	domainStr := fmt.Sprintf(`.%s`, domain)
через плюсик побыстрее работать должно

2021-04-04 20:28 UTC, merged